name: Windows
run-name: ${{github.actor}} build
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  BUILD_DIR: ${{github.workspace}}/build
  BASE_DIR: ${{github.workspace}}
  BUILD_TYPE: Release


jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v6

      - name: Create build folder
        run: mkdir build

      - name: CMake Config
        run: cmake -B $BUILD_DIR -S $BASE_DIR -G "Visual Studio 17 2022"

      - name: Build
        run: cmake --build $BUILD_DIR --config $BUILD_TYPE

      - name: Test
        run: ctest --build-config $BUILD_TYPE